### ISSUE TITLE
You need to update QtAV to support latest ffmpeg

### ISSUE THREAD

**Issue by SolarAquarion** [nejatafshar/QtAV#1]
==> Making package: qtav-git 1:v1.12.0.r115.g2ac4fdd3-1 (Tue Apr 17 13:10:50 EDT 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating QtAV git repo...
Fetching origin
==> Validating source files with sha512sums...
    QtAV ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of QtAV git repo...
Cloning into 'QtAV'...
done.
==> Starting pkgver()...
==> Updated version: qtav-git 1:v.1.12.0.r3629.d1d032e7-1
==> Starting build()...
Info: creating stash file /home/solaraquarion/pkgbuild/qtav-git/src/QtAV/.qmake.stash
Project MESSAGE: BUILD_DIR=/home/solaraquarion/pkgbuild/qtav-git/src/QtAV
Project MESSAGE: MAKEFILE_GENERATOR=UNIX
Info: creating cache file /home/solaraquarion/pkgbuild/qtav-git/src/QtAV/.qmake.cache
Project MESSAGE: target arch: x86_64
Project MESSAGE: target arch features: mmx sse sse2
Project MESSAGE: To disable config tests, you can use 1 of the following methods
Project MESSAGE: 1. create '.qmake.conf' in the root source dir, add 'CONFIG += no_config_tests'(Qt5)
Project MESSAGE: 2. pass 'CONFIG += no_config_tests' or '-config no_config_tests' to qmake
Project MESSAGE: 3. add 'CONFIG += no_config_tests' in /home/solaraquarion/pkgbuild/qtav-git/src/QtAV/user.conf
Project MESSAGE: To manually set a config test result to true, disable config tests and enable config_name like above
Checking for avutil... no
Project ERROR: avutil is required, but compiler can not find it

**Comment by SolarAquarion** [comment]
Can you tag code?

**Comment by SolarAquarion** [comment]
@nejatafshar why isn't this project counted under forks and is a original project instead?

**Comment by nejatafshar** [comment]
@SolarAquarion That's because i have added FFmpeg build files for Windows and Linux to the repository using Git LFS. You can not use LFS on forked projects.
